/**
 * Portfolio Summary PDF Template
 */
export function portfolioSummaryTemplate(data: {
  totalProjects: number;
  activeProjects: number;
  completedProjects: number;
  totalTasks: number;
  completedTasks: number;
  taskCompletionRate: number;
  totalBudget: number;
  spentBudget: number;
  budgetUtilization: number;
  totalKPIs: number;
  activeKPIs: number;
  kpiPerformanceRate: number;
  projects: Array<{
    name: string;
    code: string;
    status: string;
    taskCount: number;
    completedTaskCount: number;
    budget?: number;
  }>;
  generatedAt: string;
  generatedBy: string;
}): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Portfolio Summary Report</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #333;
      background: #fff;
      padding: 30px;
    }
    
    .header {
      text-align: center;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 3px solid #366092;
    }
    
    .header h1 {
      color: #366092;
      font-size: 28pt;
      margin-bottom: 10px;
    }
    
    .header .subtitle {
      color: #666;
      font-size: 12pt;
    }
    
    .metadata {
      text-align: right;
      font-size: 9pt;
      color: #666;
      margin-bottom: 20px;
    }
    
    .summary-cards {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 15px;
      margin-bottom: 30px;
    }
    
    .card {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    
    .card.green {
      background: linear-gradient(135deg, #00b09b 0%, #96c93d 100%);
    }
    
    .card.blue {
      background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
    }
    
    .card.orange {
      background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);
    }
    
    .card-title {
      font-size: 10pt;
      opacity: 0.9;
      margin-bottom: 8px;
    }
    
    .card-value {
      font-size: 24pt;
      font-weight: bold;
      margin-bottom: 5px;
    }
    
    .card-subtitle {
      font-size: 9pt;
      opacity: 0.8;
    }
    
    .section {
      margin-bottom: 30px;
    }
    
    .section-title {
      font-size: 16pt;
      color: #366092;
      margin-bottom: 15px;
      padding-bottom: 8px;
      border-bottom: 2px solid #e0e0e0;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 10pt;
      margin-bottom: 20px;
    }
    
    thead {
      background-color: #366092;
      color: white;
    }
    
    th {
      padding: 12px;
      text-align: left;
      font-weight: 600;
    }
    
    td {
      padding: 10px 12px;
      border-bottom: 1px solid #e0e0e0;
    }
    
    tbody tr:hover {
      background-color: #f5f5f5;
    }
    
    .status {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 12px;
      font-size: 9pt;
      font-weight: 600;
    }
    
    .status.active {
      background-color: #e3f2fd;
      color: #1976d2;
    }
    
    .status.completed {
      background-color: #e8f5e9;
      color: #388e3c;
    }
    
    .status.on-hold {
      background-color: #fff3e0;
      color: #f57c00;
    }
    
    .progress-bar {
      width: 100%;
      height: 20px;
      background-color: #e0e0e0;
      border-radius: 10px;
      overflow: hidden;
    }
    
    .progress-fill {
      height: 100%;
      background: linear-gradient(90deg, #4caf50 0%, #8bc34a 100%);
      text-align: center;
      color: white;
      font-size: 9pt;
      line-height: 20px;
      font-weight: 600;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 2px solid #e0e0e0;
      text-align: center;
      font-size: 9pt;
      color: #666;
    }
    
    .page-break {
      page-break-after: always;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>📊 Portfolio Summary Report</h1>
    <div class="subtitle">Metrika PMO System</div>
  </div>
  
  <div class="metadata">
    <div>Generated: ${data.generatedAt}</div>
    <div>Generated by: ${data.generatedBy}</div>
  </div>
  
  <div class="summary-cards">
    <div class="card blue">
      <div class="card-title">Total Projects</div>
      <div class="card-value">${data.totalProjects}</div>
      <div class="card-subtitle">${data.activeProjects} Active • ${data.completedProjects} Completed</div>
    </div>
    
    <div class="card green">
      <div class="card-title">Task Completion</div>
      <div class="card-value">${data.taskCompletionRate.toFixed(1)}%</div>
      <div class="card-subtitle">${data.completedTasks} of ${data.totalTasks} tasks</div>
    </div>
    
    <div class="card orange">
      <div class="card-title">Budget Utilization</div>
      <div class="card-value">${data.budgetUtilization.toFixed(1)}%</div>
      <div class="card-subtitle">$${(data.spentBudget / 1000).toFixed(0)}K of $${(data.totalBudget / 1000).toFixed(0)}K</div>
    </div>
  </div>
  
  <div class="section">
    <h2 class="section-title">📈 Key Performance Indicators</h2>
    <div class="summary-cards">
      <div class="card">
        <div class="card-title">Total KPIs</div>
        <div class="card-value">${data.totalKPIs}</div>
        <div class="card-subtitle">${data.activeKPIs} Active</div>
      </div>
      <div class="card green">
        <div class="card-title">KPI Performance</div>
        <div class="card-value">${data.kpiPerformanceRate.toFixed(1)}%</div>
        <div class="card-subtitle">Meeting targets</div>
      </div>
    </div>
  </div>
  
  <div class="section">
    <h2 class="section-title">📋 Projects Overview</h2>
    <table>
      <thead>
        <tr>
          <th>Project</th>
          <th>Code</th>
          <th>Status</th>
          <th>Tasks</th>
          <th>Progress</th>
          <th>Budget</th>
        </tr>
      </thead>
      <tbody>
        ${data.projects
          .map(
            (project) => `
          <tr>
            <td><strong>${project.name}</strong></td>
            <td>${project.code}</td>
            <td>
              <span class="status ${project.status.toLowerCase().replace('_', '-')}">${project.status}</span>
            </td>
            <td>${project.completedTaskCount} / ${project.taskCount}</td>
            <td>
              <div class="progress-bar">
                <div class="progress-fill" style="width: ${project.taskCount > 0 ? ((project.completedTaskCount / project.taskCount) * 100).toFixed(0) : 0}%">
                  ${project.taskCount > 0 ? ((project.completedTaskCount / project.taskCount) * 100).toFixed(0) : 0}%
                </div>
              </div>
            </td>
            <td>${project.budget ? '$' + (project.budget / 1000).toFixed(0) + 'K' : 'N/A'}</td>
          </tr>
        `
          )
          .join('')}
      </tbody>
    </table>
  </div>
  
  <div class="footer">
    <p>This report is confidential and intended for internal use only.</p>
    <p>© 2025 Metrika PMO System. All rights reserved.</p>
  </div>
</body>
</html>
  `;
}
